print("=== AA 账单分摊器 ===")
all_money= float(input("聚餐总金额: "))
people_num = int(input("请输入参与人数: "))
name_str = input("请输入每个人的名字（用逗号分隔）:")
print("-" * 23)
print(f"账单总额: {all_money:.2f}")
print(f"参与人数: {people_num}")
print(f"每个人需要支付: {all_money / people_num:.2f}")
print("-" * 23)
names_display = name_str.replace(",", " / ")
print(f"名单: {names_display}")
print("谢谢使用！")
print(str(123))